# Generated by Django 5.2.5 on 2025-09-02 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Time in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='listening/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_audios', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False/Not Given'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20)),
                ('question_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('choice_a', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_b', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.listeningaudio')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False/Not Given'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20)),
                ('question_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('choice_a', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_b', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.readingpassage')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('questions', models.TextField(help_text='Enter questions separated by new lines')),
                ('time_limit', models.PositiveIntegerField(default=5, help_text='Time in minutes')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_parts', to='exams.exam')),
            ],
            options={
                'ordering': ['part_type'],
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], default='task1', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing_images/')),
                ('min_words', models.IntegerField(default=150)),
                ('time_limit', models.PositiveIntegerField(default=20, help_text='Time in minutes')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_groups', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'unique_together': {('exam', 'group')},
            },
        ),
    ]
