# Generated by Django 5.2.8 on 2025-11-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Time in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='listening/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_audios', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multiple_answer', 'Multiple Choice Multiple Answer'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('one_word_and_or_a_number', 'One Word and/or a Number'), ('one_word_only', 'One Word Only'), ('no_word_and_or_a_number', 'No more than a Word and/or a Number')], default='mcq', max_length=50)),
                ('start_number', models.PositiveIntegerField(blank=True, null=True)),
                ('end_number', models.PositiveIntegerField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, help_text='Instructions for matching questions, etc.')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.listeningaudio')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choice_a', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_b', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_e', models.CharField(blank=True, max_length=255, null=True)),
                ('options_list', models.TextField(blank=True, help_text='For matching questions - list of options separated by new lines')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='exams.listeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('time', models.PositiveIntegerField(blank=True, default=20, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multiple_answer', 'Multiple Choice Multiple Answer'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('one_word_and_or_a_number', 'One Word and/or a Number'), ('no_word_and_or_a_number', 'No more than a Word and/or a Number'), ('one_word_only', 'One Word Only')], default='mcq', max_length=50)),
                ('start_number', models.PositiveIntegerField(blank=True, null=True)),
                ('end_number', models.PositiveIntegerField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, help_text='Instructions for matching questions, etc.')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.readingpassage')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choice_a', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_b', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_e', models.CharField(blank=True, max_length=255, null=True)),
                ('options_list', models.TextField(blank=True, help_text='For matching questions - list of options separated by new lines')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='exams.readingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('questions', models.TextField(help_text='Enter questions separated by new lines')),
                ('time_limit', models.PositiveIntegerField(default=5, help_text='Time in minutes')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_parts', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('part1', 'Part1 question'), ('part2', 'Part2 you should say'), ('part3', 'Part3 sub question')], default='part1', max_length=20)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='exams.speakingpart')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], default='task1', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing_images/')),
                ('min_words', models.IntegerField(default=150)),
                ('time_limit', models.PositiveIntegerField(default=20, help_text='Time in minutes')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_groups', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'unique_together': {('exam', 'group')},
            },
        ),
    ]
