# Generated by Django 5.2.5 on 2025-09-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeningquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='readingquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='speakingpart',
            options={},
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='question_number',
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='end_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='start_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='time',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='end_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='start_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpeakingSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('part1', 'Part1 question'), ('part2', 'Part2 you should say'), ('part3', 'Part3 sub question')], default='part1', max_length=20)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='exams.speakingpart')),
            ],
        ),
    ]
