# Generated by Django 5.2.5 on 2025-09-03 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_readingquestion_choice_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningquestion',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='choice_d',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='text',
        ),
        migrations.CreateModel(
            name='ListeningSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choice_a', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_b', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='exams.listeningquestion')),
            ],
        ),
    ]
