# Generated by Django 5.2.5 on 2025-09-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_listeningquestion_choice_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingsubquestion',
            old_name='questions',
            new_name='question',
        ),
    ]
