# Generated by Django 5.2.5 on 2025-09-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_questions_readingsubquestion_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingsubquestion',
            old_name='question',
            new_name='questions',
        ),
    ]
