# Generated by Django 5.2.5 on 2025-09-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_rename_question_readingsubquestion_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsubquestion',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingsubquestion',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
