# Generated by Django 5.2.5 on 2025-09-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_listeningsubquestion_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsubquestion',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='readingsubquestion',
            name='text',
            field=models.TextField(),
        ),
    ]
