# Generated by Django 5.2.6 on 2025-09-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_listeningsubquestion_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='instruction',
            field=models.TextField(blank=True, help_text='Instructions for matching questions, etc.'),
        ),
        migrations.AddField(
            model_name='readingsubquestion',
            name='options_list',
            field=models.TextField(blank=True, help_text='For matching questions - list of options separated by new lines'),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('true_false', 'True/False/Not Given')], default='true_false', max_length=20),
        ),
    ]
