# Generated by Django 5.2.6 on 2025-09-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_readingquestion_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsubquestion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('true_false_not_given', 'True/False/Not Given'), ('one_word_and_or_a_number', 'One Word and/or a Number')], default='true_false_not_given', max_length=50),
        ),
    ]
