# Generated by Django 5.2.6 on 2025-09-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_readingsubquestion_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsubquestion',
            name='choice_e',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('one_word_and_or_a_number', 'One Word and/or a Number'), ('matching_information', 'Matching Information'), ('matching_headings', 'Matching Headings'), ('one_word_only', 'One Word Only'), ('mcq', 'Multiple Choice'), ('mcq_multiple_answer', 'Multiple Choice Multiple Answer')], default='true_false_not_given', max_length=50),
        ),
    ]
