# Generated by Django 5.2.6 on 2025-09-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_readingsubquestion_choice_e_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsubquestion',
            name='correct_answer',
            field=models.CharField(help_text='For multiple answers, separate with commas (e.g., A,B,C)', max_length=255),
        ),
    ]
