# Generated by Django 5.2.6 on 2025-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_readingsubquestion_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsubquestion',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
    ]
