# Generated by Django 5.2.6 on 2025-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_alter_readingsubquestion_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='instruction',
            field=models.TextField(blank=True, help_text='Instructions for matching questions, etc.'),
        ),
        migrations.AddField(
            model_name='listeningsubquestion',
            name='choice_e',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listeningsubquestion',
            name='options_list',
            field=models.TextField(blank=True, help_text='For matching questions - list of options separated by new lines'),
        ),
        migrations.AddField(
            model_name='listeningsubquestion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multiple_answer', 'Multiple Choice Multiple Answer'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('fill_blank', 'Fill in the Blank'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('matching_features', 'Matching Features'), ('sentence_completion', 'Sentence Completion'), ('summary_completion', 'Summary Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion'), ('flow_chart_completion', 'Flow Chart Completion'), ('diagram_labeling', 'Diagram Labeling'), ('short_answer', 'Short Answer'), ('one_word_and_or_a_number', 'One Word and/or a Number'), ('one_word_only', 'One Word Only')], default='mcq', max_length=50),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multiple_answer', 'Multiple Choice Multiple Answer'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('fill_blank', 'Fill in the Blank'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('matching_features', 'Matching Features'), ('sentence_completion', 'Sentence Completion'), ('summary_completion', 'Summary Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion'), ('flow_chart_completion', 'Flow Chart Completion'), ('diagram_labeling', 'Diagram Labeling'), ('short_answer', 'Short Answer'), ('one_word_and_or_a_number', 'One Word and/or a Number'), ('one_word_only', 'One Word Only')], default='mcq', max_length=50),
        ),
    ]
