# Generated by Django 5.2.6 on 2025-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_alter_listeningquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multiple_answer', 'Multiple Choice Multiple Answer'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('one_word_and_or_a_number', 'One Word and/or a Number'), ('one_word_only', 'One Word Only'), ('no_word_and_or_a_number', 'No more than a Word and/or a Number')], default='mcq', max_length=50),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multiple_answer', 'Multiple Choice Multiple Answer'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('one_word_and_or_a_number', 'One Word and/or a Number'), ('no_word_and_or_a_number', 'No more than a Word and/or a Number'), ('one_word_only', 'One Word Only')], default='mcq', max_length=50),
        ),
    ]
