# Generated by Django 5.2.8 on 2025-11-11 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'profile__role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group')),
                ('student', models.OneToOneField(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'student')},
            },
        ),
    ]
