# Generated by Django 5.2.5 on 2025-09-02 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
