# Generated by Django 5.2.8 on 2025-11-11 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('submitted', 'Yuborilgan'), ('completed', 'Yakunlangan')], default='in_progress', max_length=20)),
                ('reading_score', models.FloatField(blank=True, null=True)),
                ('listening_score', models.FloatField(blank=True, null=True)),
                ('writing_score', models.FloatField(blank=True, null=True)),
                ('speaking_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_achievement', models.FloatField(blank=True, null=True)),
                ('coherence_cohesion', models.FloatField(blank=True, null=True)),
                ('lexical_resource', models.FloatField(blank=True, null=True)),
                ('grammatical_range', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField()),
                ('feedback', models.TextField()),
                ('strengths', models.TextField(blank=True, help_text='Talabaning kuchli tomonlari')),
                ('improvements', models.TextField(blank=True, help_text='Takomillashtirish joylari')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='attempts.attempt')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField(help_text='Speaking part ID')),
                ('audio_file', models.FileField(upload_to='speaking_audios/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='attempts.attempt')),
            ],
            options={
                'ordering': ['part_id'],
                'unique_together': {('attempt', 'part_id')},
            },
        ),
    ]
