# Generated by Django 5.2.5 on 2025-09-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='speaking_audios/'),
        ),
    ]
