# Generated by Django 5.2.6 on 2025-09-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_attempt_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='audio',
        ),
        migrations.CreateModel(
            name='AttemptAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField(help_text='Speaking part ID')),
                ('audio_file', models.FileField(upload_to='speaking_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='attempts.attempt')),
            ],
            options={
                'unique_together': {('attempt', 'part_id')},
            },
        ),
    ]
