# Generated by Django 5.0.4 on 2025-09-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_remove_attempt_audio_attemptaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='correct_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='incorrect_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
